server:
  port: 8090
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: praise-group
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/rocketmq-fat